#!/bin/bash

# Shared-iTunes-Library
# push changes to remote 

while read node
do
  if [ "${node#[^@]*@}" != "$HOSTNAME" ] && ping -c 1 -o -q ${node#[^@]*@} </dev/null &>/dev/null
  then
    echo "Connection established"

    #read in assets file from remote computer
    scp $node":Music/Shared-iTunes-Library/assets" .assets
    while read item
    do
      src=$item
      dst=$node":"$item
      #rsync -ru $src $dst
      echo "rsync -ru $src $dst"
    done < .assets

    rm -f .assets
  fi
done < machines

echo "Finished Shared-iTunes-Library.push Successfully"
